# Generated by Django 4.1.3 on 2023-11-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_infraestrutura_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(default=1, max_length=255)),
                ('nome_projeto', models.CharField(max_length=255)),
                ('docente_responsavel', models.CharField(max_length=255)),
                ('discente_participante', models.CharField(max_length=255)),
                ('matricula_discente', models.CharField(blank=True, max_length=50, null=True)),
                ('modalidade', models.CharField(max_length=100)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField()),
                ('fomento', models.CharField(max_length=100)),
                ('laboratorio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_lab', to='core.laboratorio')),
            ],
        ),
    ]
