# Generated by Django 4.1.3 on 2023-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimentointerno',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
