# Generated by Django 4.1.3 on 2023-01-30 19:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_autoridades_autoridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', tinymce.models.HTMLField()),
            ],
        ),
    ]
