# Generated by Django 4.1.3 on 2023-01-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='campo',
        ),
        migrations.AddField(
            model_name='editor',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
