# Generated by Django 4.1.3 on 2023-11-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_infraestrutura_tombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraestrutura',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
