# Generated by Django 4.1.3 on 2023-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_editor_ementa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtoNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('numero', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('doe_data', models.DateTimeField(auto_now_add=True)),
                ('doe_numero', models.PositiveIntegerField()),
                ('doe_secao', models.CharField(max_length=40)),
                ('doe_pagina', models.CharField(max_length=40)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usr_cadastro', models.CharField(max_length=40)),
                ('fformat_arq_pub', models.CharField(max_length=10)),
                ('fformat_arq_edit', models.CharField(max_length=10)),
                ('ementa', models.CharField(max_length=400)),
                ('texto_normativo', models.CharField(max_length=1000)),
                ('publicado', models.CharField(max_length=1)),
            ],
        ),
    ]
