# Generated by Django 4.1.3 on 2023-11-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_infraestrutura_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraestrutura',
            name='tombo',
            field=models.CharField(default='-', max_length=300, null=True, verbose_name='tombo'),
        ),
    ]
