# Generated by Django 4.1.3 on 2023-03-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_atonormativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtoNormativ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default='2000-10-10', verbose_name='Data de criação')),
                ('numero', models.PositiveIntegerField(default=2, unique=True, verbose_name='Número')),
                ('ano', models.PositiveIntegerField(default='2032', unique=True, verbose_name='Ano')),
                ('doe_data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Diário Oficial')),
                ('doe_numero', models.PositiveIntegerField(verbose_name='Número do Diário Oficial')),
                ('doe_secao', models.CharField(max_length=40, verbose_name='Seção do Diário Oficial')),
                ('doe_pagina', models.CharField(max_length=40, verbose_name='Página do Diário Oficial')),
                ('dt_cadastro', models.DateTimeField(default='2000-10-10', verbose_name='Data de cadastro')),
                ('usr_cadastro', models.CharField(default='enzo', max_length=40, verbose_name='Usuário de cadastro')),
                ('fformat_arq_pub', models.CharField(max_length=10, verbose_name='Formato do arquivo publicado')),
                ('fformat_arq_edit', models.CharField(max_length=10, verbose_name='Formato do arquivo editado')),
                ('ementa', models.TextField(max_length=400, verbose_name='Ementa')),
                ('texto_normativo', models.TextField(default='escrever', max_length=1000, verbose_name='Texto normativo')),
                ('publicado', models.CharField(default='n', max_length=1, verbose_name='Publicado')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data de alteração')),
                ('usr_alteracao', models.CharField(max_length=20, verbose_name='Usuário de alteração')),
                ('dt_publicado', models.DateField(blank=True, null=True, verbose_name='Data de publicação')),
                ('usr_publicacao', models.CharField(max_length=45, verbose_name='Usuário de publicação')),
                ('autoridade', models.CharField(default='setor', max_length=45, verbose_name='Autoridade')),
                ('assinante1', models.CharField(default='padrao', max_length=45, verbose_name='Assinante 1')),
                ('assinante2', models.CharField(max_length=45, null=True, verbose_name='Assinante 2')),
            ],
        ),
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('composicao_id', models.IntegerField(primary_key=True, serialize=False)),
                ('usario', models.CharField(max_length=80, verbose_name='Usuario')),
                ('sigla_setor', models.CharField(max_length=20, verbose_name='sigla do setor')),
                ('nome_setor', models.CharField(max_length=80, verbose_name='nome do setor')),
                ('portaria', models.TextField(max_length=80, verbose_name='caso seja uma portaria')),
                ('resolucao', models.TextField(verbose_name='caso seja uma resolucao')),
                ('boletim', models.TextField(verbose_name='caso seja uma boletim')),
            ],
        ),
        migrations.DeleteModel(
            name='AtoNormativo',
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='composicao_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.composicao', verbose_name='Emitente'),
        ),
    ]
