# Generated by Django 4.1.3 on 2023-03-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_core_atonormativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='atonormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomemo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='core_atonormativo',
        ),
    ]
