# Generated by Django 4.1.3 on 2023-03-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_core_atonormativo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atonormativo',
        ),
        migrations.DeleteModel(
            name='core_atonormativo',
        ),
    ]
