# Generated by Django 4.1.3 on 2023-03-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_atonormativo_delete_core_atonormativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicao',
            name='composicao_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
