# Generated by Django 4.1.3 on 2023-03-27 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_composicao_composicao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='ano',
            field=models.PositiveIntegerField(default=2032, unique=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2000, 10, 10, 4, 0, tzinfo=datetime.timezone.utc), verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='dt_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2000, 10, 10, 4, 0, tzinfo=datetime.timezone.utc), verbose_name='Data de cadastro'),
        ),
    ]
