# Generated by Django 4.1.3 on 2023-03-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_autoridade_delete_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='doe_numero',
            field=models.PositiveIntegerField(null=True, verbose_name='Número do Diário Oficial'),
        ),
    ]
