# Generated by Django 4.1.3 on 2023-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_atonormativ_composicao_id_delete_composicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='autoridade',
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='autoridade1',
            field=models.CharField(default='setor', max_length=45, verbose_name='Autoridade 1'),
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='autoridade2',
            field=models.CharField(default='setor', max_length=45, verbose_name='Autoridade 2'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='ano',
            field=models.PositiveIntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='numero',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número'),
        ),
    ]
