# Generated by Django 4.1.3 on 2023-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_atonormativ_autoridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='autoridade2',
            field=models.CharField(default='setor', max_length=45, null=True, verbose_name='Autoridade 2'),
        ),
    ]
