# Generated by Django 4.1.3 on 2023-03-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_atonormativ_autoridade2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='autoridade1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ato_normativ_autoridade1', to='core.autoridade', verbose_name='Autoridade 1'),
        ),
    ]
