# Generated by Django 4.1.3 on 2023-03-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_atonormativ_assinante1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='assinante1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ato_normativ_assinate1', to='core.autoridade', verbose_name='Assinante 1'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='autoridade1',
            field=models.CharField(default='setor1', max_length=45, verbose_name='Autoridade 1'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='autoridade2',
            field=models.CharField(default='setor2', max_length=45, null=True, verbose_name='Autoridade 2'),
        ),
    ]
