# Generated by Django 4.1.3 on 2023-03-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_atonormativ_assinante1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='autoridade1',
            field=models.CharField(default='setor', max_length=45, verbose_name='Autoridade 1'),
        ),
    ]
