# Generated by Django 4.1.3 on 2023-03-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_atonormativ_assinante1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='assinante1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ato_normativ_assinante1', to='core.autoridade', verbose_name='Assinante 1'),
        ),
    ]
