# Generated by Django 4.1.3 on 2023-03-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_atonormativ_assinante1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='assinante1',
            field=models.CharField(max_length=45, null=True, verbose_name='Assinante 1'),
        ),
    ]
