# Generated by Django 4.1.3 on 2023-03-31 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_composicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atonormativ',
            name='tipo_ato',
            field=models.ForeignKey(default=None, limit_choices_to={'tipo_ato__in': [('portaria', 'Portaria'), ('resolucao', 'Resolução'), ('boletim', 'Boletim')]}, on_delete=django.db.models.deletion.CASCADE, to='core.composicao', verbose_name='Tipo de Ato Normativo'),
        ),
    ]
