# Generated by Django 4.1.3 on 2023-06-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_atonormativ_tipo_ato'),
    ]

    operations = [
        migrations.AddField(
            model_name='atonormativ',
            name='status',
            field=models.CharField(choices=[('revisao', 'Revisão'), ('aprovado', 'Aprovado')], default='revisao', max_length=10),
        ),
    ]
