# Generated by Django 4.1.3 on 2023-07-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_boletimgerado_atonormativ_doe_numero_boletim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='assinante2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ato_normativ_assinante2', to='core.autoridade', verbose_name='Assinante 2'),
        ),
    ]
