# Generated by Django 4.2.2 on 2023-07-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_atonormativ_doe_numero_boletim'),
    ]

    operations = [
        migrations.AddField(
            model_name='atonormativ',
            name='boletim',
            field=models.TextField(default='escrever', max_length=1000, null=True, verbose_name='Texto normativo'),
        ),
    ]
