# Generated by Django 4.2.3 on 2023-07-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_atonormativ_boletim'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletimGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo_pdf', models.FileField(null=True, upload_to='boletins/', verbose_name='PDF do Boletim')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
