# Generated by Django 4.2.2 on 2023-07-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_boletimgerado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='boletim',
        ),
    ]
