# Generated by Django 4.2.2 on 2023-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_atonormativ_boletim'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletimgerado',
            name='portarias_fks',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
