# Generated by Django 4.2.2 on 2023-07-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_boletimgerado_portarias_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletimgerado',
            name='conteudo_pdf',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
